version: "3.9"

services:
    app:
        build: .
        container_name: barcodeReader
        ports:
            - 8080:8080
        volumes:
            - .:/usr/app
volumes:
    pgdata:
        driver: local
